name: Build and Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "back_devops/**"
      - ".github/workflows/deploy-backend.yml"
      
permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Login en GHCR
        run: echo "${{ secrets.GHCR_PATH }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Construir imagen del backend
        run: |
          docker build -t ghcr.io/danpzzz/devops_final-back:1.0.0 ./back_devops

      - name: Publicar imagen del backend
        run: |
          docker push ghcr.io/danpzzz/devops_final-back:1.0.0

      - name: Desplegar backend en VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Login en GHCR desde el VPS"
            echo "${{ secrets.GHCR_PATH }}" | docker login ghcr.io -u danpzZz --password-stdin

            echo "Descargando imagen actualizada"
            docker pull ghcr.io/danpzzz/devops_final-back:1.0.0

            echo "Desplegando backend"
            cd /opt/devops/stacks
            docker stack deploy --with-registry-auth -c backend.yml backend

            echo "Forzando actualización del servicio"
            docker service update --force --with-registry-auth --image ghcr.io/danpzzz/devops_final-back:1.0.0 backend_backend

            echo "Estado del backend"
            docker service ls